version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: dsml_pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: dsml_api
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:

